import { Inter as FontSans } from 'next/font/google'
import { cn, Toaster } from '@repo/ui'
import '@repo/ui/styles'
import type { Metadata } from 'next'

import { ThemeProvider } from '@/src/providers/ThemeProvider'
import { TooltipProvider } from '@/src/providers/TooltipProvider'
import QueryProvider from '@/src/providers/QueryProvider'
import AuthProvider from '@/src/providers/AuthProvider'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => (
  <html lang="en" suppressHydrationWarning>
    <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
      <AuthProvider>
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
            <TooltipProvider>{children}</TooltipProvider>
            <Toaster />
          </ThemeProvider>
        </QueryProvider>
      </AuthProvider>
    </body>
  </html>
)
export default RootLayout
